# frozen_string_literal: true

# Test for the advanced configuration file generated by the install generator.
# Ensures all helper methods are present and correct.

require 'test_helper'
require 'rails/generators'
require 'rails/generators/test_case'
require 'generators/rich_text_extraction/install/install_generator'
require_relative '../../support/generator_test_helper'

class ConfigurationGeneratorTest < Rails::Generators::TestCase
  include GeneratorTestHelper
  tests RichTextExtraction::Generators::InstallGenerator
  destination File.expand_path('../../../../tmp', __dir__)
  setup :prepare_destination

  def test_configuration_file_created_with_helpers
    run_generator
    assert_file 'config/rich_text_extraction.rb', /RichTextExtractionConfig/
    assert_file 'config/rich_text_extraction.rb', /generate_cache_key/
    assert_file 'config/rich_text_extraction.rb', /process_opengraph_data/
    assert_file 'config/rich_text_extraction.rb', /valid_link\?/
    assert_file 'config/rich_text_extraction.rb', /generate_excerpt/
  end
end 