# frozen_string_literal: true

# Test for the example background job generated by the install generator.
# Ensures all methods and processing logic are present and correct.

require 'test_helper'
require 'rails/generators'
require 'rails/generators/test_case'
require 'generators/rich_text_extraction/install/install_generator'
require_relative '../../support/generator_test_helper'

class JobGeneratorTest < Rails::Generators::TestCase
  include GeneratorTestHelper
  tests RichTextExtraction::Generators::InstallGenerator
  destination File.expand_path('../../../../tmp', __dir__)
  setup :prepare_destination

  def test_example_job_created_with_methods
    run_generator
    assert_file 'app/jobs/process_links_job.rb', /class ProcessLinksJob/
    assert_file 'app/jobs/process_links_job.rb', /queue_as :default/
    assert_file 'app/jobs/process_links_job.rb', /def perform/
    %w[process_link extract_opengraph_data store_link_data store_processed_data process_twitter_link process_youtube_link process_github_link process_generic_link].each do |method|
      assert_file 'app/jobs/process_links_job.rb', /def #{method}/
    end
  end
end 