# frozen_string_literal: true

# Test for the example model generated by the install generator.
# Ensures all methods and validations are present and correct.

require 'test_helper'
require 'rails/generators'
require 'rails/generators/test_case'
require 'generators/rich_text_extraction/install/install_generator'
require_relative '../../support/generator_test_helper'

class ModelGeneratorTest < Rails::Generators::TestCase
  include GeneratorTestHelper
  tests RichTextExtraction::Generators::InstallGenerator
  destination File.expand_path('../../../../tmp', __dir__)
  setup :prepare_destination

  def test_example_model_created_with_methods
    run_generator
    assert_file 'app/models/example_post.rb', /class ExamplePost/
    assert_file 'app/models/example_post.rb', /include RichTextExtraction::ExtractsRichText/
    assert_file 'app/models/example_post.rb', /has_rich_text :content/
    assert_file 'app/models/example_post.rb', /validates :title/
    assert_file 'app/models/example_post.rb', /validates :content/
    %w[extract_links extract_opengraph_data extract_social_content excerpt has_links\? link_count
       process_links_async].each do |method|
      assert_file 'app/models/example_post.rb', /def #{method}/
    end
    assert_file 'app/models/example_post.rb', /def clear_content_cache/
  end
end
