# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "RichTextExtraction: Ruby & Rails Gem for Rich Text, Markdown, and OpenGraph Extraction"
email: your-email@example.com
description: "Extract links, tags, mentions, emails, phone numbers, and OpenGraph metadata from rich text, Markdown, or ActionText in Ruby and Rails. Safe Markdown rendering, link previews, and structured data extraction."
keywords: "ruby, rails, gem, markdown, opengraph, actiontext, extraction, links, tags, mentions, emails, phone numbers, rich text, preview"
baseurl: "/rich_text_extraction" # for GitHub Pages
url: "https://ceccec.github.io" # update if you use a custom domain
twitter_username: ceccec
github_username: ceccec

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Enable Jekyll processing for GitHub Pages
enable_jekyll: true

# Include API documentation
include:
  - api

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom navigation (if supported by theme)
navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/documentation/"
  - title: "Features"
    url: "/features/"
  - title: "API Reference"
    url: "/api-reference/"
  - title: "Guides"
    url: "/blog/"
