name: Docs Automation

on:
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'bin/**'
      - 'docs/_posts/**'
      - 'Rakefile'
      - 'bin/new_changelog_post.rb'
      - 'bin/generate_tag_pages.rb'
      - 'docs/changelog.md'
      - 'docs/tag/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: bundle install
      - name: Run docs automation
        run: bundle exec rake docs:all
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose ./docs
      - name: Commit and push docs changes
        run: |
          git add docs/changelog.md docs/tag/
          git diff --cached --quiet || git commit -m "Auto-update changelog and tag pages [ci skip]"
          git push
      - name: Notify Slack (if configured)
        if: env.SLACK_WEBHOOK_URL != null
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 