name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: ./docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          echo "Docs directory:"
          ls -la docs/

      - name: Install dependencies
        run: |
          cd docs
          bundle install
          bundle exec jekyll doctor

      - name: Build Jekyll site
        run: |
          cd docs
          bundle exec jekyll build --baseurl "/rich_text_extraction" --verbose

      - name: Debug build output
        run: |
          echo "Build output:"
          ls -la docs/_site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          destination_dir: . 