name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', 'head']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.ruby-version == '3.1'
        uses: codecov/codecov-action@v3
        with:
          files: coverage/.resultset.json
          fail_ci_if_error: false

  update:
    name: Bundle Update (latest dependencies)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies (latest)
        run: |
          gem install bundler
          bundle update
      - name: Run tests
        run: bundle exec rake

  lint:
    name: RuboCop Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop

  docs:
    name: YARD Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Build YARD docs
        run: bundle exec yard doc

  security:
    name: Security Audit (bundler-audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Install bundler-audit
        run: gem install bundler-audit
      - name: Run bundler-audit
        run: bundler-audit check --update

  release:
    name: Release Gem
    needs: [test, lint, update]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Build gem
        run: gem build rich_text_extraction.gemspec
      - name: Publish to RubyGems
        run: gem push rich_text_extraction-*.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
